/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "Choices的小木屋",
  "description": "Choices的反思和总结",
  "base": "/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "/favicon.ico"
      }
    ],
    [
      "meta",
      {
        "name": "author",
        "content": "Choices"
      }
    ],
    [
      "meta",
      {
        "name": "keywords",
        "content": "vuepress 介绍"
      }
    ]
  ],
  "pages": [
    {
      "title": "Hello VuePress",
      "frontmatter": {
        "heroText": "Hero 标题",
        "tagline": "Hero 副标题",
        "actionText": "快速上手 →",
        "actionLink": "/zh/guide/",
        "features": [
          {
            "title": "简洁至上",
            "details": "以 Markdown 为中心的项目结构，以最少的配置帮助你专注于写作。"
          },
          {
            "title": "Vue驱动",
            "details": "享受 Vue + webpack 的开发体验，在 Markdown 中使用 Vue 组件，同时可以使用 Vue 来开发自定义主题。"
          },
          {
            "title": "高性能",
            "details": "VuePress 为每个页面预渲染生成静态的 HTML，同时在页面被加载的时候，将作为 SPA 运行。"
          }
        ],
        "footer": "MIT Licensed | Copyright © 2018-present Evan You"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-f476ac76",
      "path": "/",
      "lastUpdated": "2022年10月14日星期五下午4点54分",
      "lastUpdatedTimestamp": 1665737673000,
      "createdTime": 1665737673000
    },
    {
      "title": "关于我2",
      "frontmatter": {
        "navbar": false,
        "title": "关于我2"
      },
      "regularPath": "/about2.html",
      "relativePath": "about2.md",
      "key": "v-4737ed58",
      "path": "/about2.html",
      "headers": [
        {
          "level": 2,
          "title": "一级标题1",
          "slug": "一级标题1"
        },
        {
          "level": 3,
          "title": "1 二级标题",
          "slug": "_1-二级标题"
        },
        {
          "level": 2,
          "title": "一级标题1",
          "slug": "一级标题1-2"
        },
        {
          "level": 2,
          "title": "一级标题1",
          "slug": "一级标题1-3"
        }
      ],
      "lastUpdated": "2022年10月14日星期五下午2点42分",
      "lastUpdatedTimestamp": 1665729760000,
      "createdTime": 1665729760000
    },
    {
      "title": "CSS a",
      "frontmatter": {
        "title": "CSS a"
      },
      "regularPath": "/css/",
      "relativePath": "css/README.md",
      "key": "v-c9e5936c",
      "path": "/css/",
      "headers": [
        {
          "level": 2,
          "title": "你好 css",
          "slug": "你好-css"
        }
      ],
      "lastUpdated": "2022年10月14日星期五下午4点54分",
      "lastUpdatedTimestamp": 1665737673000,
      "createdTime": 1665737673000
    },
    {
      "title": "css b",
      "frontmatter": {
        "title": "css b"
      },
      "regularPath": "/css/c-bbb.html",
      "relativePath": "css/c-bbb.md",
      "key": "v-5618baae",
      "path": "/css/c-bbb.html",
      "headers": [
        {
          "level": 2,
          "title": "关于我",
          "slug": "关于我"
        },
        {
          "level": 2,
          "title": "一级标题1",
          "slug": "一级标题1"
        },
        {
          "level": 3,
          "title": "1 二级标题",
          "slug": "_1-二级标题"
        },
        {
          "level": 2,
          "title": "一级标题1",
          "slug": "一级标题1-2"
        },
        {
          "level": 2,
          "title": "一级标题1",
          "slug": "一级标题1-3"
        }
      ],
      "lastUpdated": "2022年10月14日星期五下午4点54分",
      "lastUpdatedTimestamp": 1665737673000,
      "createdTime": 1665737673000
    },
    {
      "title": "关于我",
      "frontmatter": {
        "navbar": false
      },
      "regularPath": "/about.html",
      "relativePath": "about.md",
      "key": "v-b7cccb54",
      "path": "/about.html",
      "headers": [
        {
          "level": 2,
          "title": "关于我",
          "slug": "关于我"
        },
        {
          "level": 2,
          "title": "一级标题1",
          "slug": "一级标题1"
        },
        {
          "level": 3,
          "title": "1 二级标题",
          "slug": "_1-二级标题"
        },
        {
          "level": 2,
          "title": "一级标题1",
          "slug": "一级标题1-2"
        },
        {
          "level": 2,
          "title": "一级标题1",
          "slug": "一级标题1-3"
        }
      ],
      "lastUpdated": "2022年10月14日星期五下午4点54分",
      "lastUpdatedTimestamp": 1665737673000,
      "createdTime": 1665737673000
    },
    {
      "title": "css a",
      "frontmatter": {
        "title": "css a"
      },
      "regularPath": "/css/c-aaa.html",
      "relativePath": "css/c-aaa.md",
      "key": "v-74923449",
      "path": "/css/c-aaa.html",
      "headers": [
        {
          "level": 2,
          "title": "关于我",
          "slug": "关于我"
        },
        {
          "level": 2,
          "title": "一级标题1",
          "slug": "一级标题1"
        },
        {
          "level": 3,
          "title": "1 二级标题",
          "slug": "_1-二级标题"
        },
        {
          "level": 2,
          "title": "一级标题1",
          "slug": "一级标题1-2"
        },
        {
          "level": 2,
          "title": "一级标题1",
          "slug": "一级标题1-3"
        }
      ],
      "lastUpdated": "2022年10月14日星期五下午4点54分",
      "lastUpdatedTimestamp": 1665737673000,
      "createdTime": 1665737673000
    },
    {
      "title": "css c",
      "frontmatter": {
        "title": "css c"
      },
      "regularPath": "/css/c-ccc.html",
      "relativePath": "css/c-ccc.md",
      "key": "v-35551109",
      "path": "/css/c-ccc.html",
      "headers": [
        {
          "level": 2,
          "title": "关于我",
          "slug": "关于我"
        },
        {
          "level": 2,
          "title": "一级标题1",
          "slug": "一级标题1"
        },
        {
          "level": 3,
          "title": "1 二级标题",
          "slug": "_1-二级标题"
        },
        {
          "level": 2,
          "title": "一级标题1",
          "slug": "一级标题1-2"
        },
        {
          "level": 2,
          "title": "一级标题1",
          "slug": "一级标题1-3"
        }
      ],
      "lastUpdated": "2022年10月14日星期五下午4点54分",
      "lastUpdatedTimestamp": 1665737673000,
      "createdTime": 1665737673000
    },
    {
      "title": "关于我1",
      "frontmatter": {
        "navbar": false,
        "title": "关于我1"
      },
      "regularPath": "/about1.html",
      "relativePath": "about1.md",
      "key": "v-63f136da",
      "path": "/about1.html",
      "headers": [
        {
          "level": 2,
          "title": "一级标题1",
          "slug": "一级标题1"
        },
        {
          "level": 3,
          "title": "1 二级标题",
          "slug": "_1-二级标题"
        },
        {
          "level": 2,
          "title": "一级标题1",
          "slug": "一级标题1-2"
        },
        {
          "level": 2,
          "title": "一级标题1",
          "slug": "一级标题1-3"
        }
      ],
      "lastUpdated": "2022年10月14日星期五下午4点54分",
      "lastUpdatedTimestamp": 1665737673000,
      "createdTime": 1665737673000
    },
    {
      "title": "js b",
      "frontmatter": {
        "title": "js b"
      },
      "regularPath": "/javascript/j-bbb.html",
      "relativePath": "javascript/j-bbb.md",
      "key": "v-587fc455",
      "path": "/javascript/j-bbb.html",
      "headers": [
        {
          "level": 2,
          "title": "关于我",
          "slug": "关于我"
        },
        {
          "level": 2,
          "title": "一级标题1",
          "slug": "一级标题1"
        },
        {
          "level": 3,
          "title": "1 二级标题",
          "slug": "_1-二级标题"
        },
        {
          "level": 2,
          "title": "一级标题1",
          "slug": "一级标题1-2"
        },
        {
          "level": 2,
          "title": "一级标题1",
          "slug": "一级标题1-3"
        }
      ],
      "lastUpdated": "2022年10月14日星期五下午4点54分",
      "lastUpdatedTimestamp": 1665737673000,
      "createdTime": 1665737673000
    },
    {
      "title": "js a",
      "frontmatter": {
        "title": "js a"
      },
      "regularPath": "/javascript/j-aaa.html",
      "relativePath": "javascript/j-aaa.md",
      "key": "v-e3efcf52",
      "path": "/javascript/j-aaa.html",
      "headers": [
        {
          "level": 2,
          "title": "关于我",
          "slug": "关于我"
        },
        {
          "level": 2,
          "title": "一级标题1",
          "slug": "一级标题1"
        },
        {
          "level": 3,
          "title": "1 二级标题",
          "slug": "_1-二级标题"
        },
        {
          "level": 2,
          "title": "一级标题1",
          "slug": "一级标题1-2"
        },
        {
          "level": 2,
          "title": "一级标题1",
          "slug": "一级标题1-3"
        }
      ],
      "lastUpdated": "2022年10月14日星期五下午4点54分",
      "lastUpdatedTimestamp": 1665737673000,
      "createdTime": 1665737673000
    },
    {
      "title": "js c",
      "frontmatter": {
        "title": "js c"
      },
      "regularPath": "/javascript/j-ccc.html",
      "relativePath": "javascript/j-ccc.md",
      "key": "v-22f77053",
      "path": "/javascript/j-ccc.html",
      "headers": [
        {
          "level": 2,
          "title": "关于我",
          "slug": "关于我"
        },
        {
          "level": 2,
          "title": "一级标题1",
          "slug": "一级标题1"
        },
        {
          "level": 3,
          "title": "1 二级标题",
          "slug": "_1-二级标题"
        },
        {
          "level": 2,
          "title": "一级标题1",
          "slug": "一级标题1-2"
        },
        {
          "level": 2,
          "title": "一级标题1",
          "slug": "一级标题1-3"
        }
      ],
      "lastUpdated": "2022年10月14日星期五下午4点54分",
      "lastUpdatedTimestamp": 1665737673000,
      "createdTime": 1665737673000
    }
  ],
  "themeConfig": {
    "lastUpdated": "更新时间",
    "logo": "/assets/img/hero.png",
    "nav": [
      {
        "text": "Home",
        "link": "/"
      },
      {
        "text": "Guide",
        "link": "/about/"
      },
      {
        "text": "Languages",
        "items": [
          {
            "text": "Group1",
            "items": [
              {
                "text": "Home",
                "link": "/"
              },
              {
                "text": "Guide",
                "link": "/about/"
              }
            ]
          },
          {
            "text": "Group2",
            "items": [
              {
                "text": "Home",
                "link": "/"
              },
              {
                "text": "Guide",
                "link": "/about/"
              }
            ]
          }
        ]
      },
      {
        "text": "External",
        "link": "https://google.com"
      }
    ]
  }
}